spring.application.name=SRE-DEVLOPE


spring.datasource.url=jdbc:mysql://localhost:3306/autopilot
spring.datasource.username=root
spring.datasource.password=root
# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# MYSQL DRIVER
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# HIBERNATE DIALECT
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# SERVER
server.port=8080


management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always